# Generated by Django 6.1.1 on 2026-09-22 15:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('seat_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StadiumSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Masalan: G'arbiy, Sharqiy, VIP", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Bosh'), ('RESERVED', 'Bron qilingan'), ('SOLD', 'Sotilgan')], default='AVAILABLE', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_seats', to='ilova.event')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilova.seat')),
            ],
            options={
                'unique_together': {('event', 'seat')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Tolov kutilmoqda'), ('PAID', 'Tolangan'), ('EXPIRED', 'Muddati otgan'), ('CANCELLED', 'Bekor qilingan')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('event_seats', models.ManyToManyField(related_name='orders', to='ilova.eventseat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='ilova.stadiumsector'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('sector', 'row_number', 'seat_number')},
        ),
    ]
