# Generated by Django 6.1.1 on 2026-09-22 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilova', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color_class', models.CharField(default='text-slate-400', max_length=50)),
                ('default_price', models.DecimalField(decimal_places=2, default=50000.0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='stadiumsector',
            name='name',
            field=models.CharField(help_text='Masalan: 1-sektor, 2-sektor', max_length=50),
        ),
        migrations.AddField(
            model_name='stadiumsector',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectors', to='ilova.sectorgroup'),
        ),
    ]
