# Generated by Django 6.1.1 on 2026-09-25 13:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilova', '0002_sectorgroup_alter_stadiumsector_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gates_open_at',
            field=models.DateTimeField(blank=True, help_text='Eshiklar ochilish vaqti', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, help_text="O'yin afishasi", null=True, upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='event',
            name='team1_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='event',
            name='team2_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='eventseat',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(help_text="O'yin boshlanish vaqti"),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Masalan: Neftchi vs Navbahor', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventseat',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', "Bo'sh"), ('RESERVED', 'Bron qilingan'), ('SOLD', 'Sotilgan')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', "To'lov kutilmoqda"), ('PAID', "To'langan"), ('EXPIRED', "Muddati o'tgan"), ('CANCELLED', 'Bekor qilingan')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='stadiumsector',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('is_used', models.BooleanField(default=False, help_text="Stadionga kirishda nazoratchi skaner qilsa true bo'ladi (1 marta ishlaydi)")),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('event_seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='ilova.eventseat')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ilova.order')),
            ],
        ),
    ]
