# Generated by Django 6.1.1 on 2026-09-26 04:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilova', '0003_event_gates_open_at_event_poster_event_team1_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='generated_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/qr_codes/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_uid',
            field=models.UUIDField(unique=True),
        ),
    ]
