# Generated by Django 6.1.1 on 2026-09-26 05:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilova', '0004_remove_ticket_generated_at_ticket_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
